name: Remote Server SSH

on:
  push:
    branches:
      - master  # Triggers the workflow on changes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Your commands here
          echo "Logged into the server"
          cd projects/portfolio
          docker compose kill
          docker compose up --build -d
        EOF
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
